### ISSUE TITLE
Additional capabilities in virtual network combo 

### ISSUE THREAD

**Issue by mahthi** [tabrezm/azure-portal-createuidefinition#1]
1) accept a count parameter with subnet object. 
2) allow specifying whether it's a contiguous block of IP addresses
3) allow specifying if the IP addresses needs to be passed to the template through bindings
4) return the starting address of contiguous block that is validated

**Comment by tabrezm** [comment]
1. What's the scenario for both `count` and `addressPrefixSize`? In other words, if the publisher needs some number of addresses, why would they care how big the actual subnet is?
2. OK, pending answer to #1.
3. How would you actually consume the IP address range? Is it more useful to know the starting IP address and count, or an array of IP addresses? There's two places I can see IP addresses being consumed: static private IP addresses for NICs, and passing them in to a script. But it's not obvious to me which format is more useful for both cases.
4. Pending answer to #3.

**Comment by mahthi** [comment]
1. I dont think partner solutions should care about address prefix size if they are able to request Count. It would mostly  be putting some guard rails in case the solution scales out in the future. For example: I start with 4 nodes going up to 12 nodes etc.,
3. Starting IP address and count is more helpful. To be precise, we need '10.0.1.', 'starting address - 12' and 'count as 16' instead of 10.0.1.12-16. I can't use the latter to set static IP addresses on the NIC since ARM doesnt 'split' function yet. The earlier would actually solve both scenarios - NICs and Passing to Scripts.

**Comment by tabrezm** [comment]
We actually need to keep both `count` and `addressPrefixSize` concepts since the latter is necessary for creating new virtual networks. And I agree that outputting an array of IP addresses is probably more useful, so let's introduce only this output format for now. You will already know the count since it was passed in for 1, so this shouldn't be a necessary output.

**Comment by tabrezm** [comment]
Oops.
